### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by mittman** [NeenuAVarghese/guesswhat#1]
Components
- [x] New name
- [x] Bootstrap layout
- [x] HTML5 canvas
- [x] socket.IO chat
- [x] countdown timer
- [x] chat log parsing
- [x] External dictionary API ([onelook.com](http://www.datamuse.com/api/): [npm](https://www.npmjs.com/package/datamuse))

Game logic
- [x] Pull word/phrase and definition with API
- [x] 1 player draws
- [x] Other players guess word/phrase
- [x] Sanitize input
- [x] Search chat for correct word/phrase
- [x] Timer ends each rounds
- [ ] Assign teams (4+ players)

Optional features
- [ ] Hangman score system
- [ ] Save/export drawings
- [ ] 1-player _ghost_ mode ([playback drawing](http://ramkulkarni.com/blog/record-and-playback-drawing-in-html5-canvas-part-ii/))
- [x] Private rooms
- [ ] _So You Think You Can Draw_ reverse game mode (1 player guesses; other players draw)
